"""create progression_templates

Revision ID: 9e66e712dd72
Revises: 
Create Date: 2026-04-24 19:19:23.164562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e66e712dd72'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('progression_templates',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('bars', sa.Integer(), nullable=False),
    sa.Column('time_signature', sa.Text(), nullable=False),
    sa.Column('default_bpm', sa.Integer(), nullable=False),
    sa.Column('recommended_scales', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('progression', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progression_templates_category'), 'progression_templates', ['category'], unique=False)
    op.create_index(op.f('ix_progression_templates_slug'), 'progression_templates', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_progression_templates_slug'), table_name='progression_templates')
    op.drop_index(op.f('ix_progression_templates_category'), table_name='progression_templates')
    op.drop_table('progression_templates')
    # ### end Alembic commands ###
